import 'study_item_model.dart';

List<StudyItem> studyItemStaticData = [
  StudyItem(
    keyword: "Hiragana a",
    itemType: "Hiragana",
    characterID: "あ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["a"],
  ),
  StudyItem(
    keyword: "Hiragana i",
    itemType: "Hiragana",
    characterID: "い",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["i"],
  ),
  StudyItem(
    keyword: "Hiragana u",
    itemType: "Hiragana",
    characterID: "う",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["u"],
  ),
  StudyItem(
    keyword: "Hiragana e",
    itemType: "Hiragana",
    characterID: "え",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["e"],
  ),
  StudyItem(
    keyword: "Hiragana o",
    itemType: "Hiragana",
    characterID: "お",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["o"],
  ),
  StudyItem(
    keyword: "Hiragana ka",
    itemType: "Hiragana",
    characterID: "か",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ka"],
  ),
  StudyItem(
    keyword: "Hiragana ki",
    itemType: "Hiragana",
    characterID: "き",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ki"],
  ),
  StudyItem(
    keyword: "Hiragana ku",
    itemType: "Hiragana",
    characterID: "く",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ku"],
  ),
  StudyItem(
    keyword: "Hiragana ke",
    itemType: "Hiragana",
    characterID: "け",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ke"],
  ),
  StudyItem(
    keyword: "Hiragana ko",
    itemType: "Hiragana",
    characterID: "こ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ko"],
  ),
  StudyItem(
    keyword: "Hiragana sa",
    itemType: "Hiragana",
    characterID: "さ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["sa"],
  ),
  StudyItem(
    keyword: "Hiragana shi",
    itemType: "Hiragana",
    characterID: "し",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["shi"],
  ),
  StudyItem(
    keyword: "Hiragana su",
    itemType: "Hiragana",
    characterID: "す",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["su"],
  ),
  StudyItem(
    keyword: "Hiragana se",
    itemType: "Hiragana",
    characterID: "せ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["se"],
  ),
  StudyItem(
    keyword: "Hiragana so",
    itemType: "Hiragana",
    characterID: "そ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["so"],
  ),
  StudyItem(
    keyword: "Hiragana ta",
    itemType: "Hiragana",
    characterID: "た",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ta"],
  ),
  StudyItem(
    keyword: "Hiragana chi",
    itemType: "Hiragana",
    characterID: "ち",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["chi"],
  ),
  StudyItem(
    keyword: "Hiragana tsu",
    itemType: "Hiragana",
    characterID: "つ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["tsu"],
  ),
  StudyItem(
    keyword: "Hiragana te",
    itemType: "Hiragana",
    characterID: "て",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["te"],
  ),
  StudyItem(
    keyword: "Hiragana to",
    itemType: "Hiragana",
    characterID: "と",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["to"],
  ),
  StudyItem(
    keyword: "Hiragana na",
    itemType: "Hiragana",
    characterID: "な",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["na"],
  ),
  StudyItem(
    keyword: "Hiragana ni",
    itemType: "Hiragana",
    characterID: "に",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ni"],
  ),
  StudyItem(
    keyword: "Hiragana nu",
    itemType: "Hiragana",
    characterID: "ぬ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["nu"],
  ),
  StudyItem(
    keyword: "Hiragana ne",
    itemType: "Hiragana",
    characterID: "ね",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ne"],
  ),
  StudyItem(
    keyword: "Hiragana no",
    itemType: "Hiragana",
    characterID: "の",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["no"],
  ),
  StudyItem(
    keyword: "Hiragana ha",
    itemType: "Hiragana",
    characterID: "は",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ha"],
  ),
  StudyItem(
    keyword: "Hiragana hi",
    itemType: "Hiragana",
    characterID: "ひ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["hi"],
  ),
  StudyItem(
    keyword: "Hiragana fu",
    itemType: "Hiragana",
    characterID: "ふ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["fu"],
  ),
  StudyItem(
    keyword: "Hiragana he",
    itemType: "Hiragana",
    characterID: "へ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["he"],
  ),
  StudyItem(
    keyword: "Hiragana ho",
    itemType: "Hiragana",
    characterID: "ほ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ho"],
  ),
  StudyItem(
    keyword: "Hiragana ma",
    itemType: "Hiragana",
    characterID: "ま",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ma"],
  ),
  StudyItem(
    keyword: "Hiragana mi",
    itemType: "Hiragana",
    characterID: "み",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["mi"],
  ),
  StudyItem(
    keyword: "Hiragana mu",
    itemType: "Hiragana",
    characterID: "む",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["mu"],
  ),
  StudyItem(
    keyword: "Hiragana me",
    itemType: "Hiragana",
    characterID: "め",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["me"],
  ),
  StudyItem(
    keyword: "Hiragana mo",
    itemType: "Hiragana",
    characterID: "も",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["mo"],
  ),
  StudyItem(
    keyword: "Hiragana ya",
    itemType: "Hiragana",
    characterID: "や",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ya"],
  ),
  StudyItem(
    keyword: "Hiragana yu",
    itemType: "Hiragana",
    characterID: "ゆ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["yu"],
  ),
  StudyItem(
    keyword: "Hiragana yo",
    itemType: "Hiragana",
    characterID: "よ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["yo"],
  ),
  StudyItem(
    keyword: "Hiragana ra",
    itemType: "Hiragana",
    characterID: "ら",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ra"],
  ),
  StudyItem(
    keyword: "Hiragana ri",
    itemType: "Hiragana",
    characterID: "り",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ri"],
  ),
  StudyItem(
    keyword: "Hiragana ru",
    itemType: "Hiragana",
    characterID: "る",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ru"],
  ),
  StudyItem(
    keyword: "Hiragana re",
    itemType: "Hiragana",
    characterID: "れ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["re"],
  ),
  StudyItem(
    keyword: "Hiragana ro",
    itemType: "Hiragana",
    characterID: "ろ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ro"],
  ),
  StudyItem(
    keyword: "Hiragana wa",
    itemType: "Hiragana",
    characterID: "わ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["wa"],
  ),
  StudyItem(
    keyword: "Hiragana o (wo)",
    itemType: "Hiragana",
    characterID: "を",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["o (wo)"],
  ),
  StudyItem(
    keyword: "Hiragana n",
    itemType: "Hiragana",
    characterID: "ん",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["n"],
  ),
  StudyItem(
    keyword: "Hiragana ga",
    itemType: "Hiragana",
    characterID: "が",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ga"],
  ),
  StudyItem(
    keyword: "Hiragana gi",
    itemType: "Hiragana",
    characterID: "ぎ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["gi"],
  ),
  StudyItem(
    keyword: "Hiragana gu",
    itemType: "Hiragana",
    characterID: "ぐ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["gu"],
  ),
  StudyItem(
    keyword: "Hiragana ge",
    itemType: "Hiragana",
    characterID: "げ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ge"],
  ),
  StudyItem(
    keyword: "Hiragana go",
    itemType: "Hiragana",
    characterID: "ご",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["go"],
  ),
  StudyItem(
    keyword: "Hiragana za",
    itemType: "Hiragana",
    characterID: "ざ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["za"],
  ),
  StudyItem(
    keyword: "Hiragana ji (zi)",
    itemType: "Hiragana",
    characterID: "じ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ji (zi)"],
  ),
  StudyItem(
    keyword: "Hiragana zu",
    itemType: "Hiragana",
    characterID: "ず",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["zu"],
  ),
  StudyItem(
    keyword: "Hiragana ze",
    itemType: "Hiragana",
    characterID: "ぜ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ze"],
  ),
  StudyItem(
    keyword: "Hiragana zo",
    itemType: "Hiragana",
    characterID: "ぞ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["zo"],
  ),
  StudyItem(
    keyword: "Hiragana da",
    itemType: "Hiragana",
    characterID: "だ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["da"],
  ),
  StudyItem(
    keyword: "Hiragana ji (di)",
    itemType: "Hiragana",
    characterID: "ぢ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ji (di)"],
  ),
  StudyItem(
    keyword: "Hiragana zu (du)",
    itemType: "Hiragana",
    characterID: "づ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["zu (du)"],
  ),
  StudyItem(
    keyword: "Hiragana de",
    itemType: "Hiragana",
    characterID: "で",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["de"],
  ),
  StudyItem(
    keyword: "Hiragana do",
    itemType: "Hiragana",
    characterID: "ど",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["do"],
  ),
  StudyItem(
    keyword: "Hiragana ba",
    itemType: "Hiragana",
    characterID: "ば",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ba"],
  ),
  StudyItem(
    keyword: "Hiragana bi",
    itemType: "Hiragana",
    characterID: "び",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["bi"],
  ),
  StudyItem(
    keyword: "Hiragana bu",
    itemType: "Hiragana",
    characterID: "ぶ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["bu"],
  ),
  StudyItem(
    keyword: "Hiragana be",
    itemType: "Hiragana",
    characterID: "べ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["be"],
  ),
  StudyItem(
    keyword: "Hiragana bo",
    itemType: "Hiragana",
    characterID: "ぼ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["bo"],
  ),
  StudyItem(
    keyword: "Hiragana pa",
    itemType: "Hiragana",
    characterID: "ぱ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["pa"],
  ),
  StudyItem(
    keyword: "Hiragana pi",
    itemType: "Hiragana",
    characterID: "ぴ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["pi"],
  ),
  StudyItem(
    keyword: "Hiragana pu",
    itemType: "Hiragana",
    characterID: "ぷ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["pu"],
  ),
  StudyItem(
    keyword: "Hiragana pe",
    itemType: "Hiragana",
    characterID: "ぺ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["pe"],
  ),
  StudyItem(
    keyword: "Hiragana po",
    itemType: "Hiragana",
    characterID: "ぽ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["po"],
  ),
  StudyItem(
    keyword: "Hiragana kya",
    itemType: "Hiragana",
    characterID: "きゃ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["kya"],
  ),
  StudyItem(
    keyword: "Hiragana kyu",
    itemType: "Hiragana",
    characterID: "きゅ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["kyu"],
  ),
  StudyItem(
    keyword: "Hiragana kyo",
    itemType: "Hiragana",
    characterID: "きょ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["kyo"],
  ),
  StudyItem(
    keyword: "Hiragana sha",
    itemType: "Hiragana",
    characterID: "しゃ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["sha"],
  ),
  StudyItem(
    keyword: "Hiragana shu",
    itemType: "Hiragana",
    characterID: "しゅ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["shu"],
  ),
  StudyItem(
    keyword: "Hiragana sho",
    itemType: "Hiragana",
    characterID: "しょ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["sho"],
  ),
  StudyItem(
    keyword: "Hiragana cha",
    itemType: "Hiragana",
    characterID: "ちゃ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["cha"],
  ),
  StudyItem(
    keyword: "Hiragana chu",
    itemType: "Hiragana",
    characterID: "ちゅ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["chu"],
  ),
  StudyItem(
    keyword: "Hiragana cho",
    itemType: "Hiragana",
    characterID: "ちょ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["cho"],
  ),
  StudyItem(
    keyword: "Hiragana nya",
    itemType: "Hiragana",
    characterID: "にゃ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["nya"],
  ),
  StudyItem(
    keyword: "Hiragana nyu",
    itemType: "Hiragana",
    characterID: "にゅ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["nyu"],
  ),
  StudyItem(
    keyword: "Hiragana nyo",
    itemType: "Hiragana",
    characterID: "にょ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["nyo"],
  ),
  StudyItem(
    keyword: "Hiragana hya",
    itemType: "Hiragana",
    characterID: "ひゃ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["hya"],
  ),
  StudyItem(
    keyword: "Hiragana hyu",
    itemType: "Hiragana",
    characterID: "ひゅ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["hyu"],
  ),
  StudyItem(
    keyword: "Hiragana hyo",
    itemType: "Hiragana",
    characterID: "ひょ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["hyo"],
  ),
  StudyItem(
    keyword: "Hiragana mya",
    itemType: "Hiragana",
    characterID: "みゃ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["mya"],
  ),
  StudyItem(
    keyword: "Hiragana myu",
    itemType: "Hiragana",
    characterID: "みゅ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["myu"],
  ),
  StudyItem(
    keyword: "Hiragana myo",
    itemType: "Hiragana",
    characterID: "みょ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["myo"],
  ),
  StudyItem(
    keyword: "Hiragana rya",
    itemType: "Hiragana",
    characterID: "りゃ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["rya"],
  ),
  StudyItem(
    keyword: "Hiragana ryu",
    itemType: "Hiragana",
    characterID: "りゅ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ryu"],
  ),
  StudyItem(
    keyword: "Hiragana ryo",
    itemType: "Hiragana",
    characterID: "りょ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ryo"],
  ),
  StudyItem(
    keyword: "Hiragana gya",
    itemType: "Hiragana",
    characterID: "ぎゃ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["gya"],
  ),
  StudyItem(
    keyword: "Hiragana gyu",
    itemType: "Hiragana",
    characterID: "ぎゅ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["gyu"],
  ),
  StudyItem(
    keyword: "Hiragana gyo",
    itemType: "Hiragana",
    characterID: "ぎょ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["gyo"],
  ),
  StudyItem(
    keyword: "Hiragana ja",
    itemType: "Hiragana",
    characterID: "じゃ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ja"],
  ),
  StudyItem(
    keyword: "Hiragana ju",
    itemType: "Hiragana",
    characterID: "じゅ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ju"],
  ),
  StudyItem(
    keyword: "Hiragana jo",
    itemType: "Hiragana",
    characterID: "じょ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["jo"],
  ),
  StudyItem(
    keyword: "Hiragana bya",
    itemType: "Hiragana",
    characterID: "びゃ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["bya"],
  ),
  StudyItem(
    keyword: "Hiragana byu",
    itemType: "Hiragana",
    characterID: "びゅ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["byu"],
  ),
  StudyItem(
    keyword: "Hiragana byo",
    itemType: "Hiragana",
    characterID: "びょ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["byo"],
  ),
  StudyItem(
    keyword: "Hiragana pya",
    itemType: "Hiragana",
    characterID: "ぴゃ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["pya"],
  ),
  StudyItem(
    keyword: "Hiragana pyu",
    itemType: "Hiragana",
    characterID: "ぴゅ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["pyu"],
  ),
  StudyItem(
    keyword: "Hiragana pyo",
    itemType: "Hiragana",
    characterID: "ぴょ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["pyo"],
  ),
];
