import 'package:flutter/foundation.dart';

String hiraganaList = "あいうえおかきくけこさしすせそたちつてとなにぬね" +
    "のはひふへほまみむめもやゆよらりるれろわをんがぎぐ" +
    "げござじずぜぞだぢづでどばびぶべぼぱぴぷぺぽゃゅょ";

String katakanaList = "アイウエオカキクケコサシスセソタチツテトナニヌネ" +
    "ノハヒフヘホマミムメモヤユヨラリルレロワヲンガギグゲゴザ" +
    "ジズゼゾダヂヅデドバビブベボパピプペポャュョァィェォ";

class Kana {
  final String type;
  final String reading;
  final String characterID;

  int progressLevel;
  String mnemonicStory;
  String learningStatus;
  List<String> recallHistory;
  List<String> practiceHistory;
  DateTime dateLastLevelChanged;
  int chosenDifficulty;

  Kana({
    @required this.type,
    @required this.reading,
    @required this.characterID,
    this.progressLevel = 0,
    this.mnemonicStory = "",
    this.learningStatus = "Lesson",
    this.recallHistory,
    this.practiceHistory,
    this.dateLastLevelChanged,
    this.chosenDifficulty = 1,
  });
}

List<Kana> kanjiStaticData = [
  Kana(
    reading: "a",
    type: "Hiragana",
    characterID: "あ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "i",
    type: "Hiragana",
    characterID: "い",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "u",
    type: "Hiragana",
    characterID: "う",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "e",
    type: "Hiragana",
    characterID: "え",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "o",
    type: "Hiragana",
    characterID: "お",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ka",
    type: "Hiragana",
    characterID: "か",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ki",
    type: "Hiragana",
    characterID: "き",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ku",
    type: "Hiragana",
    characterID: "く",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ke",
    type: "Hiragana",
    characterID: "け",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ko",
    type: "Hiragana",
    characterID: "こ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "sa",
    type: "Hiragana",
    characterID: "さ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "shi",
    type: "Hiragana",
    characterID: "し",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "su",
    type: "Hiragana",
    characterID: "す",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "se",
    type: "Hiragana",
    characterID: "せ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "so",
    type: "Hiragana",
    characterID: "そ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ta",
    type: "Hiragana",
    characterID: "た",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "chi",
    type: "Hiragana",
    characterID: "ち",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "tsu",
    type: "Hiragana",
    characterID: "つ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "te",
    type: "Hiragana",
    characterID: "て",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "to",
    type: "Hiragana",
    characterID: "と",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "na",
    type: "Hiragana",
    characterID: "な",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ni",
    type: "Hiragana",
    characterID: "に",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "nu",
    type: "Hiragana",
    characterID: "ぬ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ne",
    type: "Hiragana",
    characterID: "ね",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "no",
    type: "Hiragana",
    characterID: "の",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ha",
    type: "Hiragana",
    characterID: "は",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "hi",
    type: "Hiragana",
    characterID: "ひ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "fu",
    type: "Hiragana",
    characterID: "ふ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "he",
    type: "Hiragana",
    characterID: "へ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ho",
    type: "Hiragana",
    characterID: "ほ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ma",
    type: "Hiragana",
    characterID: "ま",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "mi",
    type: "Hiragana",
    characterID: "み",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "mu",
    type: "Hiragana",
    characterID: "む",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "me",
    type: "Hiragana",
    characterID: "め",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "mo",
    type: "Hiragana",
    characterID: "も",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ya",
    type: "Hiragana",
    characterID: "や",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "yu",
    type: "Hiragana",
    characterID: "ゆ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "yo",
    type: "Hiragana",
    characterID: "よ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ra",
    type: "Hiragana",
    characterID: "ら",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ri",
    type: "Hiragana",
    characterID: "り",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ru",
    type: "Hiragana",
    characterID: "る",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "re",
    type: "Hiragana",
    characterID: "れ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ro",
    type: "Hiragana",
    characterID: "ろ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "wa",
    type: "Hiragana",
    characterID: "わ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "o (wo)",
    type: "Hiragana",
    characterID: "を",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "n",
    type: "Hiragana",
    characterID: "ん",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ga",
    type: "Hiragana",
    characterID: "が",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "gi",
    type: "Hiragana",
    characterID: "ぎ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "gu",
    type: "Hiragana",
    characterID: "ぐ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ge",
    type: "Hiragana",
    characterID: "げ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "go",
    type: "Hiragana",
    characterID: "ご",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "za",
    type: "Hiragana",
    characterID: "ざ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ji (zi)",
    type: "Hiragana",
    characterID: "じ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "zu",
    type: "Hiragana",
    characterID: "ず",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ze",
    type: "Hiragana",
    characterID: "ぜ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "zo",
    type: "Hiragana",
    characterID: "ぞ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "da",
    type: "Hiragana",
    characterID: "だ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ji (di)",
    type: "Hiragana",
    characterID: "ぢ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "zu (du)",
    type: "Hiragana",
    characterID: "づ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "de",
    type: "Hiragana",
    characterID: "で",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "do",
    type: "Hiragana",
    characterID: "ど",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ba",
    type: "Hiragana",
    characterID: "ば",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "bi",
    type: "Hiragana",
    characterID: "び",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "bu",
    type: "Hiragana",
    characterID: "ぶ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "be",
    type: "Hiragana",
    characterID: "べ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "bo",
    type: "Hiragana",
    characterID: "ぼ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "pa",
    type: "Hiragana",
    characterID: "ぱ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "pi",
    type: "Hiragana",
    characterID: "ぴ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "pu",
    type: "Hiragana",
    characterID: "ぷ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "pe",
    type: "Hiragana",
    characterID: "ぺ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "po",
    type: "Hiragana",
    characterID: "ぽ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "kya",
    type: "Hiragana",
    characterID: "きゃ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "kyu",
    type: "Hiragana",
    characterID: "きゅ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "kyo",
    type: "Hiragana",
    characterID: "きょ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "sha",
    type: "Hiragana",
    characterID: "しゃ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "shu",
    type: "Hiragana",
    characterID: "しゅ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "sho",
    type: "Hiragana",
    characterID: "しょ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "cha",
    type: "Hiragana",
    characterID: "ちゃ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "chu",
    type: "Hiragana",
    characterID: "ちゅ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "cho",
    type: "Hiragana",
    characterID: "ちょ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "nya",
    type: "Hiragana",
    characterID: "にゃ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "nyu",
    type: "Hiragana",
    characterID: "にゅ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "nyo",
    type: "Hiragana",
    characterID: "にょ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "hya",
    type: "Hiragana",
    characterID: "ひゃ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "hyu",
    type: "Hiragana",
    characterID: "ひゅ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "hyo",
    type: "Hiragana",
    characterID: "ひょ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "mya",
    type: "Hiragana",
    characterID: "みゃ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "myu",
    type: "Hiragana",
    characterID: "みゅ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "myo",
    type: "Hiragana",
    characterID: "みょ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "rya",
    type: "Hiragana",
    characterID: "りゃ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ryu",
    type: "Hiragana",
    characterID: "りゅ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ryo",
    type: "Hiragana",
    characterID: "りょ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "gya",
    type: "Hiragana",
    characterID: "ぎゃ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "gyu",
    type: "Hiragana",
    characterID: "ぎゅ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "gyo",
    type: "Hiragana",
    characterID: "ぎょ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ja",
    type: "Hiragana",
    characterID: "じゃ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ju",
    type: "Hiragana",
    characterID: "じゅ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "jo",
    type: "Hiragana",
    characterID: "じょ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "bya",
    type: "Hiragana",
    characterID: "びゃ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "byu",
    type: "Hiragana",
    characterID: "びゅ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "byo",
    type: "Hiragana",
    characterID: "びょ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "pya",
    type: "Hiragana",
    characterID: "ぴゃ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "pyu",
    type: "Hiragana",
    characterID: "ぴゅ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "pyo",
    type: "Hiragana",
    characterID: "ぴょ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "a",
    type: "Katakana",
    characterID: "ア",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "i",
    type: "Katakana",
    characterID: "イ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "u",
    type: "Katakana",
    characterID: "ウ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "e",
    type: "Katakana",
    characterID: "エ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "o",
    type: "Katakana",
    characterID: "オ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ka",
    type: "Katakana",
    characterID: "カ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ki",
    type: "Katakana",
    characterID: "キ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ku",
    type: "Katakana",
    characterID: "ク",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ke",
    type: "Katakana",
    characterID: "ケ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ko",
    type: "Katakana",
    characterID: "コ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "sa",
    type: "Katakana",
    characterID: "サ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "shi",
    type: "Katakana",
    characterID: "シ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "su",
    type: "Katakana",
    characterID: "ス",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "se",
    type: "Katakana",
    characterID: "セ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "so",
    type: "Katakana",
    characterID: "ソ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ta",
    type: "Katakana",
    characterID: "タ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "chi",
    type: "Katakana",
    characterID: "チ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "tsu",
    type: "Katakana",
    characterID: "ツ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "te",
    type: "Katakana",
    characterID: "テ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "to",
    type: "Katakana",
    characterID: "ト",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "na",
    type: "Katakana",
    characterID: "ナ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ni",
    type: "Katakana",
    characterID: "ニ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "nu",
    type: "Katakana",
    characterID: "ヌ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ne",
    type: "Katakana",
    characterID: "ネ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "no",
    type: "Katakana",
    characterID: "ノ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ha",
    type: "Katakana",
    characterID: "ハ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "hi",
    type: "Katakana",
    characterID: "ヒ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "fu",
    type: "Katakana",
    characterID: "フ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "he",
    type: "Katakana",
    characterID: "ヘ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ho",
    type: "Katakana",
    characterID: "ホ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ma",
    type: "Katakana",
    characterID: "マ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "mi",
    type: "Katakana",
    characterID: "ミ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "mu",
    type: "Katakana",
    characterID: "ム",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "me",
    type: "Katakana",
    characterID: "メ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "mo",
    type: "Katakana",
    characterID: "モ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ya",
    type: "Katakana",
    characterID: "ヤ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "yu",
    type: "Katakana",
    characterID: "ユ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "yo",
    type: "Katakana",
    characterID: "ヨ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ra",
    type: "Katakana",
    characterID: "ラ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ri",
    type: "Katakana",
    characterID: "リ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ru",
    type: "Katakana",
    characterID: "ル",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "re",
    type: "Katakana",
    characterID: "レ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ro",
    type: "Katakana",
    characterID: "ロ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "wa",
    type: "Katakana",
    characterID: "ワ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "o (wo)",
    type: "Katakana",
    characterID: "ヲ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "n",
    type: "Katakana",
    characterID: "ン",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ga",
    type: "Katakana",
    characterID: "ガ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "gi",
    type: "Katakana",
    characterID: "ギ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "gu",
    type: "Katakana",
    characterID: "グ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ge",
    type: "Katakana",
    characterID: "ゲ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "go",
    type: "Katakana",
    characterID: "ゴ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "za",
    type: "Katakana",
    characterID: "ザ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ji (zi)",
    type: "Katakana",
    characterID: "ジ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "zu",
    type: "Katakana",
    characterID: "ズ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ze",
    type: "Katakana",
    characterID: "ゼ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "zo",
    type: "Katakana",
    characterID: "ゾ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "da",
    type: "Katakana",
    characterID: "ダ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ji (di)",
    type: "Katakana",
    characterID: "ヂ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "zu (du)",
    type: "Katakana",
    characterID: "ヅ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "de",
    type: "Katakana",
    characterID: "デ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "do",
    type: "Katakana",
    characterID: "ド",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ba",
    type: "Katakana",
    characterID: "バ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "bi",
    type: "Katakana",
    characterID: "ビ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "bu",
    type: "Katakana",
    characterID: "ブ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "be",
    type: "Katakana",
    characterID: "ベ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "bo",
    type: "Katakana",
    characterID: "ボ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "pa",
    type: "Katakana",
    characterID: "パ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "pi",
    type: "Katakana",
    characterID: "ピ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "pu",
    type: "Katakana",
    characterID: "プ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "pe",
    type: "Katakana",
    characterID: "ペ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "po",
    type: "Katakana",
    characterID: "ポ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "kya",
    type: "Katakana",
    characterID: "キャ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "kyu",
    type: "Katakana",
    characterID: "キュ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "kyo",
    type: "Katakana",
    characterID: "キョ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "sha",
    type: "Katakana",
    characterID: "シャ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "shu",
    type: "Katakana",
    characterID: "シュ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "sho",
    type: "Katakana",
    characterID: "ショ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "cha",
    type: "Katakana",
    characterID: "チャ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "chu",
    type: "Katakana",
    characterID: "チュ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "cho",
    type: "Katakana",
    characterID: "チョ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "nya",
    type: "Katakana",
    characterID: "ニャ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "nyu",
    type: "Katakana",
    characterID: "ニュ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "nyo",
    type: "Katakana",
    characterID: "ニョ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "hya",
    type: "Katakana",
    characterID: "ヒャ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "hyu",
    type: "Katakana",
    characterID: "ヒュ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "hyo",
    type: "Katakana",
    characterID: "ヒョ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "mya",
    type: "Katakana",
    characterID: "ミャ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "myu",
    type: "Katakana",
    characterID: "ミュ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "myo",
    type: "Katakana",
    characterID: "ミョ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "rya",
    type: "Katakana",
    characterID: "リャ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ryu",
    type: "Katakana",
    characterID: "リュ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ryo",
    type: "Katakana",
    characterID: "リョ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "gya",
    type: "Katakana",
    characterID: "ギャ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "gyu",
    type: "Katakana",
    characterID: "ギュ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "gyo",
    type: "Katakana",
    characterID: "ギョ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ja",
    type: "Katakana",
    characterID: "ジャ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "ju",
    type: "Katakana",
    characterID: "ジュ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "jo",
    type: "Katakana",
    characterID: "ジョ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "bya",
    type: "Katakana",
    characterID: "ビャ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "byu",
    type: "Katakana",
    characterID: "ビュ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "byo",
    type: "Katakana",
    characterID: "ビョ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "pya",
    type: "Katakana",
    characterID: "ピャ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "pyu",
    type: "Katakana",
    characterID: "ピュ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
  Kana(
    reading: "pyo",
    type: "Katakana",
    characterID: "ピョ",
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
  ),
];
