import 'study_item_model.dart';

List<StudyItem> studyItemStaticData = [
  StudyItem(
    keyword: "Katakana a",
    itemType: "Katakana",
    characterID: "ア",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["a"],
  ),
  StudyItem(
    keyword: "Katakana i",
    itemType: "Katakana",
    characterID: "イ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["i"],
  ),
  StudyItem(
    keyword: "Katakana u",
    itemType: "Katakana",
    characterID: "ウ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["u"],
  ),
  StudyItem(
    keyword: "Katakana e",
    itemType: "Katakana",
    characterID: "エ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["e"],
  ),
  StudyItem(
    keyword: "Katakana o",
    itemType: "Katakana",
    characterID: "オ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["o"],
  ),
  StudyItem(
    keyword: "Katakana ka",
    itemType: "Katakana",
    characterID: "カ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ka"],
  ),
  StudyItem(
    keyword: "Katakana ki",
    itemType: "Katakana",
    characterID: "キ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ki"],
  ),
  StudyItem(
    keyword: "Katakana ku",
    itemType: "Katakana",
    characterID: "ク",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ku"],
  ),
  StudyItem(
    keyword: "Katakana ke",
    itemType: "Katakana",
    characterID: "ケ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ke"],
  ),
  StudyItem(
    keyword: "Katakana ko",
    itemType: "Katakana",
    characterID: "コ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ko"],
  ),
  StudyItem(
    keyword: "Katakana sa",
    itemType: "Katakana",
    characterID: "サ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["sa"],
  ),
  StudyItem(
    keyword: "Katakana shi",
    itemType: "Katakana",
    characterID: "シ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["shi"],
  ),
  StudyItem(
    keyword: "Katakana su",
    itemType: "Katakana",
    characterID: "ス",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["su"],
  ),
  StudyItem(
    keyword: "Katakana se",
    itemType: "Katakana",
    characterID: "セ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["se"],
  ),
  StudyItem(
    keyword: "Katakana so",
    itemType: "Katakana",
    characterID: "ソ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["so"],
  ),
  StudyItem(
    keyword: "Katakana ta",
    itemType: "Katakana",
    characterID: "タ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ta"],
  ),
  StudyItem(
    keyword: "Katakana chi",
    itemType: "Katakana",
    characterID: "チ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["chi"],
  ),
  StudyItem(
    keyword: "Katakana tsu",
    itemType: "Katakana",
    characterID: "ツ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["tsu"],
  ),
  StudyItem(
    keyword: "Katakana te",
    itemType: "Katakana",
    characterID: "テ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["te"],
  ),
  StudyItem(
    keyword: "Katakana to",
    itemType: "Katakana",
    characterID: "ト",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["to"],
  ),
  StudyItem(
    keyword: "Katakana na",
    itemType: "Katakana",
    characterID: "ナ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["na"],
  ),
  StudyItem(
    keyword: "Katakana ni",
    itemType: "Katakana",
    characterID: "ニ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ni"],
  ),
  StudyItem(
    keyword: "Katakana nu",
    itemType: "Katakana",
    characterID: "ヌ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["nu"],
  ),
  StudyItem(
    keyword: "Katakana ne",
    itemType: "Katakana",
    characterID: "ネ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ne"],
  ),
  StudyItem(
    keyword: "Katakana no",
    itemType: "Katakana",
    characterID: "ノ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["no"],
  ),
  StudyItem(
    keyword: "Katakana ha",
    itemType: "Katakana",
    characterID: "ハ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ha"],
  ),
  StudyItem(
    keyword: "Katakana hi",
    itemType: "Katakana",
    characterID: "ヒ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["hi"],
  ),
  StudyItem(
    keyword: "Katakana fu",
    itemType: "Katakana",
    characterID: "フ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["fu"],
  ),
  StudyItem(
    keyword: "Katakana he",
    itemType: "Katakana",
    characterID: "ヘ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["he"],
  ),
  StudyItem(
    keyword: "Katakana ho",
    itemType: "Katakana",
    characterID: "ホ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ho"],
  ),
  StudyItem(
    keyword: "Katakana ma",
    itemType: "Katakana",
    characterID: "マ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ma"],
  ),
  StudyItem(
    keyword: "Katakana mi",
    itemType: "Katakana",
    characterID: "ミ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["mi"],
  ),
  StudyItem(
    keyword: "Katakana mu",
    itemType: "Katakana",
    characterID: "ム",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["mu"],
  ),
  StudyItem(
    keyword: "Katakana me",
    itemType: "Katakana",
    characterID: "メ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["me"],
  ),
  StudyItem(
    keyword: "Katakana mo",
    itemType: "Katakana",
    characterID: "モ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["mo"],
  ),
  StudyItem(
    keyword: "Katakana ya",
    itemType: "Katakana",
    characterID: "ヤ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ya"],
  ),
  StudyItem(
    keyword: "Katakana yu",
    itemType: "Katakana",
    characterID: "ユ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["yu"],
  ),
  StudyItem(
    keyword: "Katakana yo",
    itemType: "Katakana",
    characterID: "ヨ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["yo"],
  ),
  StudyItem(
    keyword: "Katakana ra",
    itemType: "Katakana",
    characterID: "ラ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ra"],
  ),
  StudyItem(
    keyword: "Katakana ri",
    itemType: "Katakana",
    characterID: "リ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ri"],
  ),
  StudyItem(
    keyword: "Katakana ru",
    itemType: "Katakana",
    characterID: "ル",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ru"],
  ),
  StudyItem(
    keyword: "Katakana re",
    itemType: "Katakana",
    characterID: "レ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["re"],
  ),
  StudyItem(
    keyword: "Katakana ro",
    itemType: "Katakana",
    characterID: "ロ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ro"],
  ),
  StudyItem(
    keyword: "Katakana wa",
    itemType: "Katakana",
    characterID: "ワ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["wa"],
  ),
  StudyItem(
    keyword: "Katakana o (wo)",
    itemType: "Katakana",
    characterID: "ヲ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["o (wo)"],
  ),
  StudyItem(
    keyword: "Katakana n",
    itemType: "Katakana",
    characterID: "ン",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["n"],
  ),
  StudyItem(
    keyword: "Katakana ga",
    itemType: "Katakana",
    characterID: "ガ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ga"],
  ),
  StudyItem(
    keyword: "Katakana gi",
    itemType: "Katakana",
    characterID: "ギ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["gi"],
  ),
  StudyItem(
    keyword: "Katakana gu",
    itemType: "Katakana",
    characterID: "グ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["gu"],
  ),
  StudyItem(
    keyword: "Katakana ge",
    itemType: "Katakana",
    characterID: "ゲ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ge"],
  ),
  StudyItem(
    keyword: "Katakana go",
    itemType: "Katakana",
    characterID: "ゴ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["go"],
  ),
  StudyItem(
    keyword: "Katakana za",
    itemType: "Katakana",
    characterID: "ザ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["za"],
  ),
  StudyItem(
    keyword: "Katakana ji (zi)",
    itemType: "Katakana",
    characterID: "ジ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ji (zi)"],
  ),
  StudyItem(
    keyword: "Katakana zu",
    itemType: "Katakana",
    characterID: "ズ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["zu"],
  ),
  StudyItem(
    keyword: "Katakana ze",
    itemType: "Katakana",
    characterID: "ゼ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ze"],
  ),
  StudyItem(
    keyword: "Katakana zo",
    itemType: "Katakana",
    characterID: "ゾ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["zo"],
  ),
  StudyItem(
    keyword: "Katakana da",
    itemType: "Katakana",
    characterID: "ダ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["da"],
  ),
  StudyItem(
    keyword: "Katakana ji (di)",
    itemType: "Katakana",
    characterID: "ヂ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ji (di)"],
  ),
  StudyItem(
    keyword: "Katakana zu (du)",
    itemType: "Katakana",
    characterID: "ヅ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["zu (du)"],
  ),
  StudyItem(
    keyword: "Katakana de",
    itemType: "Katakana",
    characterID: "デ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["de"],
  ),
  StudyItem(
    keyword: "Katakana do",
    itemType: "Katakana",
    characterID: "ド",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["do"],
  ),
  StudyItem(
    keyword: "Katakana ba",
    itemType: "Katakana",
    characterID: "バ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ba"],
  ),
  StudyItem(
    keyword: "Katakana bi",
    itemType: "Katakana",
    characterID: "ビ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["bi"],
  ),
  StudyItem(
    keyword: "Katakana bu",
    itemType: "Katakana",
    characterID: "ブ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["bu"],
  ),
  StudyItem(
    keyword: "Katakana be",
    itemType: "Katakana",
    characterID: "ベ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["be"],
  ),
  StudyItem(
    keyword: "Katakana bo",
    itemType: "Katakana",
    characterID: "ボ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["bo"],
  ),
  StudyItem(
    keyword: "Katakana pa",
    itemType: "Katakana",
    characterID: "パ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["pa"],
  ),
  StudyItem(
    keyword: "Katakana pi",
    itemType: "Katakana",
    characterID: "ピ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["pi"],
  ),
  StudyItem(
    keyword: "Katakana pu",
    itemType: "Katakana",
    characterID: "プ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["pu"],
  ),
  StudyItem(
    keyword: "Katakana pe",
    itemType: "Katakana",
    characterID: "ペ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["pe"],
  ),
  StudyItem(
    keyword: "Katakana po",
    itemType: "Katakana",
    characterID: "ポ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["po"],
  ),
  StudyItem(
    keyword: "Katakana kya",
    itemType: "Katakana",
    characterID: "キャ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["kya"],
  ),
  StudyItem(
    keyword: "Katakana kyu",
    itemType: "Katakana",
    characterID: "キュ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["kyu"],
  ),
  StudyItem(
    keyword: "Katakana kyo",
    itemType: "Katakana",
    characterID: "キョ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["kyo"],
  ),
  StudyItem(
    keyword: "Katakana sha",
    itemType: "Katakana",
    characterID: "シャ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["sha"],
  ),
  StudyItem(
    keyword: "Katakana shu",
    itemType: "Katakana",
    characterID: "シュ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["shu"],
  ),
  StudyItem(
    keyword: "Katakana sho",
    itemType: "Katakana",
    characterID: "ショ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["sho"],
  ),
  StudyItem(
    keyword: "Katakana cha",
    itemType: "Katakana",
    characterID: "チャ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["cha"],
  ),
  StudyItem(
    keyword: "Katakana chu",
    itemType: "Katakana",
    characterID: "チュ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["chu"],
  ),
  StudyItem(
    keyword: "Katakana cho",
    itemType: "Katakana",
    characterID: "チョ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["cho"],
  ),
  StudyItem(
    keyword: "Katakana nya",
    itemType: "Katakana",
    characterID: "ニャ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["nya"],
  ),
  StudyItem(
    keyword: "Katakana nyu",
    itemType: "Katakana",
    characterID: "ニュ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["nyu"],
  ),
  StudyItem(
    keyword: "Katakana nyo",
    itemType: "Katakana",
    characterID: "ニョ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["nyo"],
  ),
  StudyItem(
    keyword: "Katakana hya",
    itemType: "Katakana",
    characterID: "ヒャ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["hya"],
  ),
  StudyItem(
    keyword: "Katakana hyu",
    itemType: "Katakana",
    characterID: "ヒュ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["hyu"],
  ),
  StudyItem(
    keyword: "Katakana hyo",
    itemType: "Katakana",
    characterID: "ヒョ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["hyo"],
  ),
  StudyItem(
    keyword: "Katakana mya",
    itemType: "Katakana",
    characterID: "ミャ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["mya"],
  ),
  StudyItem(
    keyword: "Katakana myu",
    itemType: "Katakana",
    characterID: "ミュ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["myu"],
  ),
  StudyItem(
    keyword: "Katakana myo",
    itemType: "Katakana",
    characterID: "ミョ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["myo"],
  ),
  StudyItem(
    keyword: "Katakana rya",
    itemType: "Katakana",
    characterID: "リャ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["rya"],
  ),
  StudyItem(
    keyword: "Katakana ryu",
    itemType: "Katakana",
    characterID: "リュ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ryu"],
  ),
  StudyItem(
    keyword: "Katakana ryo",
    itemType: "Katakana",
    characterID: "リョ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ryo"],
  ),
  StudyItem(
    keyword: "Katakana gya",
    itemType: "Katakana",
    characterID: "ギャ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["gya"],
  ),
  StudyItem(
    keyword: "Katakana gyu",
    itemType: "Katakana",
    characterID: "ギュ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["gyu"],
  ),
  StudyItem(
    keyword: "Katakana gyo",
    itemType: "Katakana",
    characterID: "ギョ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["gyo"],
  ),
  StudyItem(
    keyword: "Katakana ja",
    itemType: "Katakana",
    characterID: "ジャ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ja"],
  ),
  StudyItem(
    keyword: "Katakana ju",
    itemType: "Katakana",
    characterID: "ジュ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["ju"],
  ),
  StudyItem(
    keyword: "Katakana jo",
    itemType: "Katakana",
    characterID: "ジョ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["jo"],
  ),
  StudyItem(
    keyword: "Katakana bya",
    itemType: "Katakana",
    characterID: "ビャ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["bya"],
  ),
  StudyItem(
    keyword: "Katakana byu",
    itemType: "Katakana",
    characterID: "ビュ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["byu"],
  ),
  StudyItem(
    keyword: "Katakana byo",
    itemType: "Katakana",
    characterID: "ビョ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["byo"],
  ),
  StudyItem(
    keyword: "Katakana pya",
    itemType: "Katakana",
    characterID: "ピャ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["pya"],
  ),
  StudyItem(
    keyword: "Katakana pyu",
    itemType: "Katakana",
    characterID: "ピュ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["pyu"],
  ),
  StudyItem(
    keyword: "Katakana pyo",
    itemType: "Katakana",
    characterID: "ピョ",
    jlptLevel: "N5",
    frameNumFifth: 0,
    frameNumSixth: 0,
    buildingBlocksID: [],
    buildingBlockKeywords: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    similarCharactersID: [],
    similarCharactersKeyword: [],
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    itemMeanings: [],
    itemReadings: ["pyo"],
  ),
];
