import 'package:kanji_quiz_app/model/kanji_model.dart';

List<Kanji> kanjiStaticData = [
  Kanji(
    keyword: "Five",
    itemType: "Kanji",
    jlptLevel: "N5",
    frameNumForth: 5,
    frameNumSixth: 5,
    characterID: "五",
    buildingBlocksLook: [],
    buildingBlockKeywords: [],
    similarCharactersLook: ["吾", "悟"],
    similarCharactersKeyword: ["I", "Enlightenment"],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 71,
    kanjiMeanings: ["Five"],
  ),
  Kanji(
    keyword: "Ten",
    itemType: "Kanji",
    jlptLevel: "N5",
    frameNumForth: 10,
    frameNumSixth: 10,
    characterID: "十",
    buildingBlocksLook: [],
    buildingBlockKeywords: [],
    similarCharactersLook: ["干", "千"],
    similarCharactersKeyword: ["Dry", "Thousand"],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 32,
    kanjiMeanings: ["Ten"],
  ),
  Kanji(
    keyword: "Mouth",
    itemType: "Kanji",
    jlptLevel: "N4",
    frameNumForth: 11,
    frameNumSixth: 11,
    characterID: "口",
    buildingBlocksLook: [],
    buildingBlockKeywords: [],
    similarCharactersLook: ["回", "固"],
    similarCharactersKeyword: ["Times", "Harden"],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 89,
    kanjiMeanings: ["Mouth"],
  ),
  Kanji(
    keyword: "Sun",
    itemType: "Kanji",
    jlptLevel: "N5",
    frameNumForth: 12,
    frameNumSixth: 12,
    characterID: "日",
    buildingBlocksLook: [],
    buildingBlockKeywords: [],
    similarCharactersLook: ["旧", "旦"],
    similarCharactersKeyword: ["Old times", "Daybreak"],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 5,
    kanjiMeanings: ["day", "sun", "Japan", "counter for days"],
  ),
  Kanji(
    keyword: "Moon",
    itemType: "Kanji",
    jlptLevel: "N5",
    frameNumForth: 13,
    frameNumSixth: 13,
    characterID: "月",
    buildingBlocksLook: [],
    buildingBlockKeywords: [],
    similarCharactersLook: ["朋", "肌"],
    similarCharactersKeyword: ["Companion", "Texture"],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 47,
    kanjiMeanings: ["month", "moon"],
  ),
  Kanji(
    keyword: "Oneself",
    itemType: "Kanji",
    jlptLevel: "N5",
    frameNumForth: 17,
    frameNumSixth: 17,
    characterID: "吾",
    buildingBlocksLook: ["五", "口"],
    buildingBlockKeywords: ["Five", "Mouth"],
    similarCharactersLook: ["悟"],
    similarCharactersKeyword: ["Enlightenment"],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 553,
    kanjiMeanings: ["I", "my", "our", "one's own"],
  ),
  Kanji(
    keyword: "Bright",
    itemType: "Kanji",
    jlptLevel: "N3",
    frameNumForth: 20,
    frameNumSixth: 20,
    characterID: "明",
    buildingBlocksLook: ["日", "月"],
    buildingBlockKeywords: ["Sun", "Moon"],
    similarCharactersLook: ["胆", "脂"],
    similarCharactersKeyword: ["Gall bladder", "Fat"],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 72,
    kanjiMeanings: ["bright", "light"],
  ),
  Kanji(
    keyword: "Goods",
    itemType: "Kanji",
    jlptLevel: "N3",
    frameNumForth: 23,
    frameNumSixth: 23,
    characterID: "品",
    buildingBlocksLook: ["口"],
    buildingBlockKeywords: ["Mouth"],
    similarCharactersLook: [],
    similarCharactersKeyword: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 282,
    kanjiMeanings: ["goods", "refinement", "dignity", "article"],
  ),
  Kanji(
    keyword: "Top hat",
    itemType: "Radical",
    jlptLevel: "",
    frameNumForth: 0,
    frameNumSixth: 20128,
    characterID: "亠",
    buildingBlocksLook: [],
    buildingBlockKeywords: [],
    similarCharactersLook: [],
    similarCharactersKeyword: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 4759,
    kanjiMeanings: [],
  ),
  Kanji(
    keyword: "Garment",
    itemType: "Kanji",
    jlptLevel: "N2",
    frameNumForth: 423,
    frameNumSixth: 423,
    characterID: "衣",
    buildingBlocksLook: ["亠"],
    buildingBlockKeywords: ["Top hat"],
    similarCharactersLook: ["衰", "依"],
    similarCharactersKeyword: ["Decline", "Reliant"],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 627,
    kanjiMeanings: ["garment", "clothes", "dressing"],
  ),
  Kanji(
    keyword: "Pathetic",
    itemType: "Kanji",
    jlptLevel: "N1",
    frameNumForth: 428,
    frameNumSixth: 428,
    characterID: "哀",
    buildingBlocksLook: ["亠", "口", "衣"],
    buildingBlockKeywords: ["Top hat", "Mouth", "Garment"],
    similarCharactersLook: ["喪", "衰"],
    similarCharactersKeyword: ["Mourning", "Decline"],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 971,
    kanjiMeanings: [
      "pathetic",
      "grief",
      "sorrow",
      "pathos",
      "pity",
      "sympathize",
    ],
  ),
  Kanji(
    keyword: "Road",
    itemType: "Primitive",
    jlptLevel: "",
    frameNumForth: 0,
    frameNumSixth: 0,
    characterID: "assets/images/badge_295p_xl.png",
    buildingBlocksLook: [],
    buildingBlockKeywords: [],
    similarCharactersLook: [],
    similarCharactersKeyword: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    kanjiMeanings: [],
  ),
  Kanji(
    keyword: "Scarecrow",
    itemType: "Primitive",
    jlptLevel: "",
    frameNumForth: 0,
    frameNumSixth: 0,
    characterID: "assets/images/badge_1700p_xl.png",
    buildingBlocksLook: [],
    buildingBlockKeywords: [],
    similarCharactersLook: [],
    similarCharactersKeyword: [],
    dateLastLevelChanged: DateTime.now().subtract(Duration(days: 5)),
    recallHistory: [],
    practiceHistory: [],
    frequencyInAozora: 0,
    kanjiMeanings: [],
  ),
];
