class KanjiMap {
  List<Map<String, Object>> _initalMap = [
    {
      'itemId': '五',
      'keyword': 'Five',
      'frameNumber': '5',
      'mnemonicStory': '',
      'progressLevel': 5,
      'learningStatus': 'Learned',
      'buildingBlocks': [],
      'greyPhotoAddress': 'assets/images/5_Kanji_xlg.png',
      'colorPhotoAddress': 'assets/images/5_Kanji_xl.png',
      'buildBlocksAddress': [],
    },
    {
      'itemId': '口',
      'keyword': 'Mouth',
      'frameNumber': '11',
      'mnemonicStory': '',
      'progressLevel': 2,
      'learningStatus': 'Review',
      'buildingBlocks': [],
      'greyPhotoAddress': 'assets/images/11_Kanji_xlg.png',
      'colorPhotoAddress': 'assets/images/11_Kanji_xl.png',
      'buildBlocksAddress': [],
    },
    {
      'itemId': '日',
      'keyword': 'Sun',
      'frameNumber': '12',
      'mnemonicStory': '',
      'progressLevel': 3,
      'learningStatus': 'Review',
      'buildingBlocks': [],
      'greyPhotoAddress': 'assets/images/12_Kanji_xlg.png',
      'colorPhotoAddress': 'assets/images/12_Kanji_xl.png',
      'buildBlocksAddress': [],
    },
    {
      'itemId': '月',
      'keyword': 'Moon',
      'frameNumber': '13',
      'mnemonicStory': '',
      'progressLevel': 4,
      'learningStatus': 'Review',
      'buildingBlocks': [],
      'greyPhotoAddress': 'assets/images/13_Kanji_xlg.png',
      'colorPhotoAddress': 'assets/images/13_Kanji_xl.png',
      'buildBlocksAddress': [],
    },
    {
      'itemId': '亠',
      'keyword': 'Top hat',
      'frameNumber': '20128',
      'mnemonicStory': '',
      'progressLevel': 1,
      'learningStatus': 'Review',
      'buildingBlocks': [],
      'greyPhotoAddress': 'assets/images/218_Kanji_xlg.png',
      'colorPhotoAddress': 'assets/images/218_Kanji_xl.png',
      'buildBlocksAddress': [],
    },
    {
      'itemId': '衣',
      'keyword': 'Garment',
      'frameNumber': '423',
      'mnemonicStory': '',
      'progressLevel': 1,
      'learningStatus': 'Review',
      'buildingBlocks': ['Top hat'],
      'greyPhotoAddress': 'assets/images/284_Kanji_xlg.png',
      'colorPhotoAddress': 'assets/images/284_Kanji_xl.png',
      'buildBlocksAddress': ['assets/images/218_Kanji_xl.png'],
    },
    {
      'itemId': '十',
      'keyword': 'Ten',
      'frameNumber': '10',
      'mnemonicStory': '',
      'progressLevel': 0,
      'learningStatus': 'Lesson',
      'buildingBlocks': [],
      'greyPhotoAddress': 'assets/images/10_Kanji_xlg.png',
      'colorPhotoAddress': 'assets/images/10_Kanji_xl.png',
      'buildBlocksAddress': [],
    },
    {
      'itemId': '吾',
      'keyword': 'Oneself',
      'frameNumber': '17',
      'mnemonicStory': '',
      'progressLevel': 0,
      'learningStatus': 'Lesson',
      'buildingBlocks': ['Five, Mouth'],
      'greyPhotoAddress': 'assets/images/17_Kanji_xlg.png',
      'colorPhotoAddress': 'assets/images/17_Kanji_xl.png',
      'buildBlocksAddress': [
        'assets/images/5_Kanji_xl.png',
        'assets/images/11_Kanji_xl.png'
      ],
    },
    {
      'itemId': '明',
      'keyword': 'Bright',
      'frameNumber': '20',
      'mnemonicStory': '',
      'progressLevel': 0,
      'learningStatus': 'Lesson',
      'buildingBlocks': ['Sun, Moon'],
      'greyPhotoAddress': 'assets/images/18_Kanji_xlg.png',
      'colorPhotoAddress': 'assets/images/18_Kanji_xl.png',
      'buildBlocksAddress': [
        'assets/images/12_Kanji_xl.png',
        'assets/images/13_Kanji_xl.png'
      ],
    },
    {
      'itemId': '品',
      'keyword': 'Goods',
      'frameNumber': '23',
      'mnemonicStory': '',
      'progressLevel': 0,
      'learningStatus': 'Lesson',
      'buildingBlocks': ['Mouth'],
      'greyPhotoAddress': 'assets/images/19_Kanji_xlg.png',
      'colorPhotoAddress': 'assets/images/19_Kanji_xl.png',
      'buildBlocksAddress': ['assets/images/11_Kanji_xl.png'],
    },
    {
      'itemId': '哀',
      'keyword': 'Pathetic',
      'frameNumber': '428',
      'mnemonicStory': '',
      'progressLevel': 0,
      'learningStatus': 'Lesson',
      'buildingBlocks': ['Top hat, Mouth, Garment'],
      'greyPhotoAddress': 'assets/images/287_Kanji_xlg.png',
      'colorPhotoAddress': 'assets/images/287_Kanji_xl.png',
      'buildBlocksAddress': [
        'assets/images/218_Kanji_xl.png',
        'assets/images/11_Kanji_xl.png',
        'assets/images/284_Kanji_xl.png',
      ],
    }
  ];

  List<Map<String, Object>> get initialKanjiMap {
    return _initalMap;
  }
}
