class KanjiMap {
  List<Map<String, Object>> _initalMap = [
    // {
    //   'itemId': '五',
    //   'keyword': 'Five',
    //   'itemType': 'Primitive Kanji',
    //   'frameNumber': '5',
    //   'mnemonicStory': '',
    //   'progressLevel': 5,
    //   'learningStatus': 'Learned',
    //   'buildingBlocks': [],
    //   'greyPhotoAddress': 'assets/images/5_Kanji_xlg.png',
    //   'colorPhotoAddress': 'assets/images/5_Kanji_xl.png',
    //   'buildBlocksAddress': [],
    //   'dateLastLevelChanged': DateTime.now().subtract(Duration(days: 5)),
    // },
    // {
    //   'itemId': '口',
    //   'keyword': 'Mouth',
    //   'itemType': 'Primitive Kanji',
    //   'frameNumber': '11',
    //   'mnemonicStory': '',
    //   'progressLevel': 4,
    //   'learningStatus': 'Review',
    //   'buildingBlocks': [],
    //   'greyPhotoAddress': 'assets/images/11_Kanji_xlg.png',
    //   'colorPhotoAddress': 'assets/images/11_Kanji_xl.png',
    //   'buildBlocksAddress': [],
    //   'dateLastLevelChanged': DateTime.now().subtract(Duration(days: 1)),
    // },
    // {
    //   'itemId': '日',
    //   'keyword': 'Sun',
    //   'itemType': 'Primitive Kanji',
    //   'frameNumber': '12',
    //   'mnemonicStory': '',
    //   'progressLevel': 3,
    //   'learningStatus': 'Review',
    //   'buildingBlocks': [],
    //   'greyPhotoAddress': 'assets/images/12_Kanji_xlg.png',
    //   'colorPhotoAddress': 'assets/images/12_Kanji_xl.png',
    //   'buildBlocksAddress': [],
    //   'dateLastLevelChanged': DateTime.now().subtract(Duration(days: 1)),
    // },
    // {
    //   'itemId': '月',
    //   'keyword': 'Moon',
    //   'itemType': 'Primitive Kanji',
    //   'frameNumber': '13',
    //   'mnemonicStory': '',
    //   'progressLevel': 2,
    //   'learningStatus': 'Review',
    //   'buildingBlocks': [],
    //   'greyPhotoAddress': 'assets/images/13_Kanji_xlg.png',
    //   'colorPhotoAddress': 'assets/images/13_Kanji_xl.png',
    //   'buildBlocksAddress': [],
    //   'dateLastLevelChanged': DateTime.now().subtract(Duration(days: 1)),
    // },
    // {
    //   'itemId': '亠',
    //   'keyword': 'Top hat',
    //   'itemType': 'Radical',
    //   'frameNumber': '20128',
    //   'mnemonicStory': '',
    //   'progressLevel': 1,
    //   'learningStatus': 'Review',
    //   'buildingBlocks': [],
    //   'greyPhotoAddress': 'assets/images/218_Kanji_xlg.png',
    //   'colorPhotoAddress': 'assets/images/218_Kanji_xl.png',
    //   'buildBlocksAddress': [],
    //   'dateLastLevelChanged': DateTime.now().subtract(Duration(days: 1)),
    // },
    // {
    //   'itemId': '衣',
    //   'keyword': 'Garment',
    //   'itemType': 'Kanji',
    //   'frameNumber': '423',
    //   'mnemonicStory': '',
    //   'progressLevel': 1,
    //   'learningStatus': 'Review',
    //   'buildingBlocks': ['Top hat'],
    //   'greyPhotoAddress': 'assets/images/284_Kanji_xlg.png',
    //   'colorPhotoAddress': 'assets/images/284_Kanji_xl.png',
    //   'buildBlocksAddress': ['assets/images/218_Kanji_xl.png'],
    //   'dateLastLevelChanged': DateTime.now().subtract(Duration(days: 1)),
    // },
    // {
    //   'itemId': '十',
    //   'keyword': 'Ten',
    //   'itemType': 'Primitive Kanji',
    //   'frameNumber': '10',
    //   'mnemonicStory': '',
    //   'progressLevel': 0,
    //   'learningStatus': 'Lesson',
    //   'buildingBlocks': [],
    //   'greyPhotoAddress': 'assets/images/10_Kanji_xlg.png',
    //   'colorPhotoAddress': 'assets/images/10_Kanji_xl.png',
    //   'buildBlocksAddress': [],
    //   'dateLastLevelChanged': DateTime.now().add(Duration(days: 100)),
    // },
    // {
    //   'itemId': '吾',
    //   'keyword': 'Oneself',
    //   'itemType': 'Kanji',
    //   'frameNumber': '17',
    //   'mnemonicStory': '',
    //   'progressLevel': 0,
    //   'learningStatus': 'Lesson',
    //   'buildingBlocks': ['Five, Mouth'],
    //   'greyPhotoAddress': 'assets/images/17_Kanji_xlg.png',
    //   'colorPhotoAddress': 'assets/images/17_Kanji_xl.png',
    //   'buildBlocksAddress': [
    //     'assets/images/5_Kanji_xl.png',
    //     'assets/images/11_Kanji_xl.png'
    //   ],
    //   'dateLastLevelChanged': DateTime.now().add(Duration(days: 100)),
    // },
    // {
    //   'itemId': '明',
    //   'keyword': 'Bright',
    //   'itemType': 'Kanji',
    //   'frameNumber': '20',
    //   'mnemonicStory': '',
    //   'progressLevel': 0,
    //   'learningStatus': 'Lesson',
    //   'buildingBlocks': ['Sun, Moon'],
    //   'greyPhotoAddress': 'assets/images/18_Kanji_xlg.png',
    //   'colorPhotoAddress': 'assets/images/18_Kanji_xl.png',
    //   'buildBlocksAddress': [
    //     'assets/images/12_Kanji_xl.png',
    //     'assets/images/13_Kanji_xl.png'
    //   ],
    //   'dateLastLevelChanged': DateTime.now().add(Duration(days: 100)),
    // },
    {
      'itemId': '品',
      'keyword': 'Goods',
      'itemType': 'Kanji',
      'frameNumber': '23',
      'mnemonicStory': '',
      'progressLevel': 0,
      'learningStatus': 'Lesson',
      'buildingBlocks': ['Mouth'],
      'greyPhotoAddress': 'assets/images/19_Kanji_xlg.png',
      'colorPhotoAddress': 'assets/images/19_Kanji_xl.png',
      'buildBlocksId': ['口'],
      'dateLastLevelChanged': DateTime.now().add(Duration(days: 100)),
    },
    {
      'itemId': '哀',
      'keyword': 'Pathetic',
      'itemType': 'Kanji',
      'frameNumber': '428',
      'mnemonicStory': '',
      'progressLevel': 0,
      'learningStatus': 'Lesson',
      'buildingBlocks': ['Top hat, Mouth, Garment'],
      'greyPhotoAddress': 'assets/images/287_Kanji_xlg.png',
      'colorPhotoAddress': 'assets/images/287_Kanji_xl.png',
      'buildBlocksId': [
        '亠',
        '口',
        '衣',
      ],
      'dateLastLevelChanged': DateTime.now().add(Duration(days: 100)),
    }
  ];

  List<Map<String, Object>> get initialKanjiMap {
    return _initalMap;
  }
}
